export const dogs = [
  {
    id: 1,
    name: 'Biscuit',
    age: '3 years',
    gender: 'Male',
    weight: '8 lbs',
    status: 'available',
    description: 'Biscuit is a sweet, fluffy orange Pomeranian who loves belly rubs and cuddling on the couch. He gets along well with other dogs and is house-trained.',
    personality: ['Playful', 'Affectionate', 'Gentle'],
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=600&fit=crop',
    medicalNotes: 'Neutered, up-to-date on vaccinations, dental cleaning completed.',
  },
  {
    id: 2,
    name: 'Daisy',
    age: '5 years',
    gender: 'Female',
    weight: '6 lbs',
    status: 'available',
    description: 'Daisy is a gentle soul rescued from a hoarding situation. She has blossomed into a confident, loving companion who adores long naps and short walks.',
    personality: ['Calm', 'Loyal', 'Sweet'],
    image: 'https://images.unsplash.com/photo-1583337130417-13104dec14a7?w=600&h=600&fit=crop',
    medicalNotes: 'Spayed, all vaccinations current, heartworm negative.',
  },
  {
    id: 3,
    name: 'Teddy',
    age: '2 years',
    gender: 'Male',
    weight: '7 lbs',
    status: 'available',
    description: 'Teddy is an energetic little boy with the biggest smile. He loves toys, treats, and meeting new friends at the dog park.',
    personality: ['Energetic', 'Friendly', 'Smart'],
    image: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=600&h=600&fit=crop',
    medicalNotes: 'Neutered, microchipped, all vaccinations current.',
  },
  {
    id: 4,
    name: 'Mochi',
    age: '4 years',
    gender: 'Female',
    weight: '5 lbs',
    status: 'pending',
    description: 'Mochi is a tiny cream Pomeranian who was surrendered when her owner could no longer care for her. She is looking for a quiet home with lots of love.',
    personality: ['Shy', 'Loving', 'Quiet'],
    image: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=600&fit=crop',
    medicalNotes: 'Spayed, dental work completed, on joint supplements.',
  },
  {
    id: 5,
    name: 'Charlie',
    age: '6 years',
    gender: 'Male',
    weight: '9 lbs',
    status: 'available',
    description: 'Charlie is a senior boy with so much love to give. He enjoys gentle walks, sunny spots by the window, and being near his people.',
    personality: ['Gentle', 'Loyal', 'Relaxed'],
    image: 'https://images.unsplash.com/photo-1587764379873-97837921fd44?w=600&h=600&fit=crop',
    medicalNotes: 'Neutered, senior blood work clear, on heart medication.',
  },
  {
    id: 6,
    name: 'Luna',
    age: '1 year',
    gender: 'Female',
    weight: '4 lbs',
    status: 'available',
    description: 'Luna is our youngest rescue — a tiny bundle of energy and sass! She loves zoomies, squeaky toys, and will make you laugh every day.',
    personality: ['Sassy', 'Playful', 'Curious'],
    image: 'https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?w=600&h=600&fit=crop',
    medicalNotes: 'Spayed, microchipped, up-to-date on all vaccinations.',
  },
]

export const successStories = [
  {
    id: 1,
    dogName: 'Rusty',
    family: 'The Johnson Family',
    story: 'Rusty came to us matted and scared after being found wandering the streets. After months of foster care and love, he found his forever home with the Johnsons. Now he rules the house and sleeps on a king-sized bed!',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=400&fit=crop',
  },
  {
    id: 2,
    dogName: 'Ginger',
    family: 'Sarah & Mike',
    story: 'Ginger was rescued from a puppy mill where she had never known a gentle touch. With patience and love from her fosters, she learned to trust again. Sarah and Mike adopted her and she now has two doggy siblings!',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop',
  },
  {
    id: 3,
    dogName: 'Peanut',
    family: 'Grandma Rose',
    story: 'Peanut, a senior Pom with a heart of gold, needed a calm home. Grandma Rose, 78, was looking for a gentle companion. It was love at first sight — they spend their days watching TV and taking slow strolls together.',
    image: 'https://images.unsplash.com/photo-1544568100-847a948585b9?w=600&h=400&fit=crop',
  },
]

export const events = [
  {
    id: 1,
    title: 'Pom Adoption Day',
    date: 'April 15, 2026',
    time: '10:00 AM - 4:00 PM',
    location: 'Central Park Dog Run, Dallas TX',
    description: 'Meet our adorable adoptable Poms in person! Bring the whole family and find your new best friend.',
    type: 'adoption',
  },
  {
    id: 2,
    title: 'Foster Orientation Workshop',
    date: 'April 22, 2026',
    time: '2:00 PM - 4:00 PM',
    location: 'Virtual (Zoom)',
    description: 'Learn everything you need to know about fostering a Pomeranian. Open to anyone interested in opening their home to a rescue.',
    type: 'workshop',
  },
  {
    id: 3,
    title: 'Pomeranians & Pancakes Fundraiser',
    date: 'May 3, 2026',
    time: '9:00 AM - 12:00 PM',
    location: 'Sunshine Café, Fort Worth TX',
    description: 'Join us for a morning of fluffy pancakes and even fluffier Pomeranians! All proceeds support our rescue operations.',
    type: 'fundraiser',
  },
  {
    id: 4,
    title: 'Pom Walk for a Cause',
    date: 'May 17, 2026',
    time: '8:00 AM - 11:00 AM',
    location: 'White Rock Lake, Dallas TX',
    description: 'Walk with your pom (or borrow one of ours!) to raise funds for veterinary care. Prizes for top fundraisers!',
    type: 'fundraiser',
  },
]

export const stats = [
  { value: '500+', label: 'Dogs Rescued' },
  { value: '450+', label: 'Happy Adoptions' },
  { value: '100+', label: 'Active Fosters' },
  { value: '15+', label: 'Years Saving Poms' },
]

export const teamMembers = [
  {
    name: 'Emily Carter',
    role: 'Founder & Director',
    bio: 'Emily founded Recycled Pomeranians after rescuing her first Pom from a shelter. Her passion drives every rescue.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop',
  },
  {
    name: 'Dr. Sarah Kim',
    role: 'Veterinary Advisor',
    bio: 'Dr. Kim donates her veterinary expertise to ensure every rescue receives top-notch medical care.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&h=300&fit=crop',
  },
  {
    name: 'Marcus Rivera',
    role: 'Foster Coordinator',
    bio: 'Marcus matches each rescue with the perfect foster family and provides ongoing support throughout their journey.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
  },
]
